---
roles:
  hosts:
    provisioners:
      - {type: hosts}

  2-cpus:
    providers:
      - type: virtualbox
        customize:
        - [modifyvm, !ruby/sym id, '--cpus', 2]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']

  4-cpus:
    providers:
      - type: virtualbox
        customize:
        - [modifyvm, !ruby/sym id, '--cpus', 4]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']

  trusted_fact_aio_pe:
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/puppet; cp /vagrant/trusted_facts/aio_pe_csr_attributes.yaml /etc/puppetlabs/puppet/csr_attributes.yaml'

  trusted_fact_gitlab:
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/puppet; cp /vagrant/trusted_facts/gitlab_csr_attributes.yaml /etc/puppetlabs/puppet/csr_attributes.yaml'

  install_gitlab:
    provisioners:
      - type: shell
        inline: "yum install git -y"
      - type: shell
        inline: "cd /etc/puppetlabs/code/environments/production; rm -rf rampup_profile_gitlab; git clone https://github.com/PuppetLabs-RampUpProgram/RampUp_profile_gitlab;"
      - type: shell
        inline: "puppet module install vshn/gitlab; puppet apply -e 'include rampup_profile_gitlab'"

  trusted_fact_stash:
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/puppet; cp /vagrant/trusted_facts/stash_csr_attributes.yaml /etc/puppetlabs/puppet/csr_attributes.yaml'

  run_r10k:
    provisioners: 
      - type: shell
        inline: 'sleep 60; rm /etc/puppetlabs/code/environments/production/.git -f; /opt/puppetlabs/bin/r10k deploy environment -pv; sleep 60; /opt/puppetlabs/bin/puppet agent -t'

  auto_net:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
 
  master382:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
        version: '3.8.2' 

  agent_382:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_bootstrap
        master: 'master382-centos'
        version: '3.8.2'

  ssh_key:
    provisioners:
      - type: shell
        inline: "/opt/puppetlabs/bin/puppet apply /vagrant/puppet_code/ssh_key_placement.pp"

  deploy_everything:
    provisioners:
      - type: shell
        inline: "puppet agent -t; puppet agent -t; r10k deploy environment -pv; echo 'code_manager_mv_old_code=true' > /opt/puppetlabs/facter/facts.d/code_manager_mv_old_code.txt; puppet agent -t; puppet agent -t; puppet agent -t"

  master:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
        answer_extras:
          - "q_puppetmaster_r10k_remote='git@gitlab-server-ankeny:puppet/control-repo.git'"
        #  - "q_puppetmaster_r10k_private_key='/etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa'"
          - "q_puppetmaster_r10k_private_key='/etc/puppetlabs/puppetserver/code_manager.key'"

  agent:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_agent
        master_vm: 'puppet-master-ankeny'

  master201523:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
        version: '2015.2.3'

  agent201523:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_bootstrap
        version: '2015.2.3'
        master: 'puppet-master-201523'

  master20152:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
        version: '2015.2.0'
        answer_file: 'answer_files/aio.answer'

  agent20152:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_bootstrap
        version: '2015.2.0'
        master: 'puppet-master'

  windows_base:
    communicator: "winrm"
    forwarded_ports:
      - { guest: 5985, host: 5986 }
      - { guest: 3389, host: 3390 }
 
  windows_agent_20152:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: pe_bootstrap
        version: '4.0.0'
        master: 'master20152-centos'
 
  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}

  centos: 
    provisioners:
      - type: shell
        inline: 'service iptables stop; chkconfig iptables off;'
      - type: shell
        inline: '/usr/bin/yum install telnet -y' 
      - type: shell
        inline: '/usr/bin/yum install tree -y' 

  centos7: 
    provisioners:
      - type: shell
        inline: '/usr/bin/yum install telnet -y' 
      - type: shell
        inline: '/usr/bin/yum install vim -y' 
      - type: shell
        inline: '/usr/bin/yum install tree -y' 
      - type: shell
        inline: 'systemctl stop firewalld.service; systemctl disable firewalld.service'
 
  customize_pe_via_hiera: 
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/code/environments/production/hieradata; cp /vagrant/config/hierafiles/defaults.yaml /etc/puppetlabs/code/environments/production/hieradata/common.yaml'
      - type: shell
        inline: 'mkdir -p /var/lib/hiera; cp /vagrant/config/hierafiles/defaults.yaml /var/lib/hiera/defaults.yaml'  

  customize_pe_via_hiera_2015:
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/code/environments/production/hieradata; cp /vagrant/config/hierafiles/defaults.yaml /etc/puppetlabs/code/environments/production/hieradata/common.yaml'
      - type: shell
        inline: 'mkdir -p /var/lib/hiera; cp /vagrant/config/hierafiles/defaults.yaml /var/lib/hiera/defaults.yaml'

  

