---
vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.
  - name: puppet-master-201711
    hostname: puppet-master-201711.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - pe-forward-console
      - deploy_everything
      - ssh_key
      - master201711
      - pe-memory-tuning2
      - trusted_fact_aio_pe
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - 4gb-memory
      - base

  - name: puppet-master-201621
    hostname: puppet-master-201621.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - pe-forward-console
      - deploy_everything
      - ssh_key
      - master201621
      - pe-memory-tuning2
      - trusted_fact_aio_pe
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - 4gb-memory
      - base

#  - name: puppet-master-201612
#    hostname: puppet-master-201612.puppetdebug.vlan
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - pe-forward-console
#      - run_r10k
#      - deploy_everything
#      - ssh_key
#      - burnside_master
#      - pe-memory-tuning2
#      - trusted_fact_aio_pe
#      - el-stop-firewall
#      - el-fix-path
#      - medium-size
#      - 2gb-memory
#      - base

#  - name: puppet-master-201533
#    hostname: puppet-master-201533.puppetdebug.vlan
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - pe-forward-console
#      - run_r10k
#      - deploy_everything
#      - ssh_key
#      - ankeny_master
#      - pe-memory-tuning2
#      - trusted_fact_aio_pe
#      - el-stop-firewall
#      - el-fix-path
#      - medium-size
#      - 2gb-memory
#      - base

#  - name: puppet-master-201523
#    hostname: puppet-master-201523.puppetdebug.vlan
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - pe-forward-console
#      - run_r10k
#      - deploy_everything
#      - ssh_key
#      - master201523
#      - pe-memory-tuning2
#      - trusted_fact_aio_pe
#      - el-stop-firewall
#      - el-fix-path
#      - medium-size
#      - 2gb-memory
#      - base

  - name: gitlab-server
    hostname: gitlab-server.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - install_gitlab
      - agent
      - trusted_fact_gitlab
      - el-stop-firewall
      - el-fix-path
      - small-size
      - base

  - name: stash-server
    hostname: stash-server.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - agent
      - trusted_fact_stash
      - el-stop-firewall
      - el-fix-path
      - small-size
      - base



# vim: set ft=yaml:
