---
vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.
  - name: puppet-master
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - pe-forward-console
      - run_r10k
      - master201522
      - pe-memory-tuning2
      - trusted_fact_aio_pe
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base
      - '2-cpus'

  - name: gitlab-server 
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - agent201522
      - trusted_fact_gitlab
      - el-stop-firewall
      - el-fix-path
      - base

  - name: stash-server
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - agent201522
      - trusted_fact_stash
      - el-stop-firewall
      - el-fix-path
      - base



# vim: set ft=yaml:
